"""core sharing schema

Revision ID: 0001
Revises:
Create Date: 2026-10-05 19:22:04.638807
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("roll_no", sa.String(length=32), nullable=True),
        sa.Column("hostel", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("email = lower(email)", name=op.f("ck_users_email_lowercase")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "contacts",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("contact_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "accepted",
                name="contact_status",
                native_enum=False,
                create_constraint=False,
                length=16,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'accepted') = (accepted_at IS NOT NULL)",
            name=op.f("ck_contacts_accepted_at_matches_status"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'accepted')", name=op.f("ck_contacts_contact_status")
        ),
        sa.CheckConstraint("owner_id <> contact_user_id", name=op.f("ck_contacts_not_self")),
        sa.ForeignKeyConstraint(
            ["contact_user_id"],
            ["users.id"],
            name=op.f("fk_contacts_contact_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_contacts_owner_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contacts")),
        sa.UniqueConstraint(
            "owner_id", "contact_user_id", name=op.f("uq_contacts_owner_id_contact_user_id")
        ),
    )
    op.create_index(
        op.f("ix_contacts_contact_user_id"), "contacts", ["contact_user_id"], unique=False
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(), nullable=False),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "octet_length(token_hash) = 32", name=op.f("ck_refresh_tokens_token_hash_len")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    op.create_index(
        op.f("ix_refresh_tokens_family_id"), "refresh_tokens", ["family_id"], unique=False
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "share_sessions",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("sharer_id", sa.Uuid(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "outing",
                "tab_live",
                "pairing",
                "manual",
                name="share_source",
                native_enum=False,
                create_constraint=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "ends_when",
            sa.Enum(
                "until_return",
                "tab_closed",
                "until_revoked",
                "duration",
                name="ends_when",
                native_enum=False,
                create_constraint=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "ended",
                "revoked",
                name="session_status",
                native_enum=False,
                create_constraint=False,
                length=16,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("ended_reason", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'active') = (ended_at IS NULL)",
            name=op.f("ck_share_sessions_ended_at_matches_status"),
        ),
        sa.CheckConstraint(
            "ends_when IN ('until_return', 'tab_closed', 'until_revoked', 'duration')",
            name=op.f("ck_share_sessions_ends_when"),
        ),
        sa.CheckConstraint(
            "source IN ('outing', 'tab_live', 'pairing', 'manual')",
            name=op.f("ck_share_sessions_share_source"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'ended', 'revoked')",
            name=op.f("ck_share_sessions_session_status"),
        ),
        sa.CheckConstraint("ends_at > created_at", name=op.f("ck_share_sessions_ends_after_start")),
        sa.ForeignKeyConstraint(
            ["sharer_id"],
            ["users.id"],
            name=op.f("fk_share_sessions_sharer_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_share_sessions")),
    )
    op.create_index(
        "ix_share_sessions_active_ends_at",
        "share_sessions",
        ["ends_at"],
        unique=False,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_index(
        "ix_share_sessions_sharer_status", "share_sessions", ["sharer_id", "status"], unique=False
    )
    op.create_table(
        "locations",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lng", sa.Float(), nullable=False),
        sa.Column("accuracy_m", sa.Float(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("accuracy_m >= 0", name=op.f("ck_locations_accuracy_non_negative")),
        sa.CheckConstraint("lat BETWEEN -90 AND 90", name=op.f("ck_locations_lat_range")),
        sa.CheckConstraint("lng BETWEEN -180 AND 180", name=op.f("ck_locations_lng_range")),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["share_sessions.id"],
            name=op.f("fk_locations_session_id_share_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("session_id", name=op.f("pk_locations")),
    )
    op.create_table(
        "share_codes",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("code_hash", sa.LargeBinary(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "expires_at > created_at", name=op.f("ck_share_codes_expires_after_create")
        ),
        sa.CheckConstraint(
            "octet_length(code_hash) = 32", name=op.f("ck_share_codes_code_hash_len")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_share_codes_created_by_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["share_sessions.id"],
            name=op.f("fk_share_codes_session_id_share_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_share_codes")),
        sa.UniqueConstraint("code_hash", name=op.f("uq_share_codes_code_hash")),
    )
    op.create_index(op.f("ix_share_codes_session_id"), "share_codes", ["session_id"], unique=False)
    op.create_table(
        "share_viewers",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("viewer_user_id", sa.Uuid(), nullable=True),
        sa.Column("guest_label", sa.String(length=40), nullable=True),
        sa.Column("guest_token_hash", sa.LargeBinary(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "granted",
                "revoked",
                name="viewer_status",
                native_enum=False,
                create_constraint=False,
                length=16,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status <> 'granted' OR granted_at IS NOT NULL",
            name=op.f("ck_share_viewers_granted_has_timestamp"),
        ),
        sa.CheckConstraint(
            "status <> 'revoked' OR revoked_at IS NOT NULL",
            name=op.f("ck_share_viewers_revoked_has_timestamp"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'granted', 'revoked')",
            name=op.f("ck_share_viewers_viewer_status"),
        ),
        sa.CheckConstraint(
            "(viewer_user_id IS NULL) <> (guest_token_hash IS NULL)",
            name=op.f("ck_share_viewers_exactly_one_identity"),
        ),
        sa.CheckConstraint(
            "guest_token_hash IS NULL OR guest_label IS NOT NULL",
            name=op.f("ck_share_viewers_guest_has_label"),
        ),
        sa.CheckConstraint(
            "octet_length(guest_token_hash) = 32",
            name=op.f("ck_share_viewers_guest_token_hash_len"),
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["share_sessions.id"],
            name=op.f("fk_share_viewers_session_id_share_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["viewer_user_id"],
            ["users.id"],
            name=op.f("fk_share_viewers_viewer_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_share_viewers")),
        sa.UniqueConstraint("guest_token_hash", name=op.f("uq_share_viewers_guest_token_hash")),
        sa.UniqueConstraint(
            "session_id", "viewer_user_id", name=op.f("uq_share_viewers_session_id_viewer_user_id")
        ),
    )
    op.create_index(
        op.f("ix_share_viewers_viewer_user_id"), "share_viewers", ["viewer_user_id"], unique=False
    )
    op.create_table(
        "access_log",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("viewer_id", sa.Uuid(), nullable=False),
        sa.Column(
            "channel",
            sa.Enum(
                "http",
                "ws",
                name="access_channel",
                native_enum=False,
                create_constraint=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "viewed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint("channel IN ('http', 'ws')", name=op.f("ck_access_log_access_channel")),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["share_sessions.id"],
            name=op.f("fk_access_log_session_id_share_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["viewer_id"],
            ["share_viewers.id"],
            name=op.f("fk_access_log_viewer_id_share_viewers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_log")),
    )
    op.create_index(
        "ix_access_log_session_viewed", "access_log", ["session_id", "viewed_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_access_log_session_viewed", table_name="access_log")
    op.drop_table("access_log")
    op.drop_index(op.f("ix_share_viewers_viewer_user_id"), table_name="share_viewers")
    op.drop_table("share_viewers")
    op.drop_index(op.f("ix_share_codes_session_id"), table_name="share_codes")
    op.drop_table("share_codes")
    op.drop_table("locations")
    op.drop_index("ix_share_sessions_sharer_status", table_name="share_sessions")
    op.drop_index(
        "ix_share_sessions_active_ends_at",
        table_name="share_sessions",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_table("share_sessions")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_family_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_contacts_contact_user_id"), table_name="contacts")
    op.drop_table("contacts")
    op.drop_table("users")
    # ### end Alembic commands ###
