"""shared rate limiter: one row per attempt, keys stored as HMAC

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-05 21:09:30.909501
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0005"
down_revision: str | Sequence[str] | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rate_limit_hits",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("key_hash", sa.LargeBinary(), nullable=False),
        sa.Column("hit_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "octet_length(key_hash) = 32", name=op.f("ck_rate_limit_hits_key_hash_len")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rate_limit_hits")),
    )
    op.create_index("ix_rate_limit_hits_hit_at", "rate_limit_hits", ["hit_at"], unique=False)
    op.create_index(
        "ix_rate_limit_hits_lookup",
        "rate_limit_hits",
        ["scope", "key_hash", "hit_at"],
        unique=False,
    )
    # ### end Alembic commands ###
    # Every table denies Supabase's Data API (see 0002).
    op.execute("ALTER TABLE rate_limit_hits ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_rate_limit_hits_lookup", table_name="rate_limit_hits")
    op.drop_index("ix_rate_limit_hits_hit_at", table_name="rate_limit_hits")
    op.drop_table("rate_limit_hits")
    # ### end Alembic commands ###
