"""outings: one open outing per student, enforced by a partial unique index

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-05 21:17:32.607816
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0006"
down_revision: str | Sequence[str] | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outings",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("destination", sa.String(length=100), nullable=True),
        sa.Column("purpose", sa.String(length=200), nullable=True),
        sa.Column(
            "left_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("expected_return_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("returned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "expected_return_at > left_at", name=op.f("ck_outings_expected_after_leaving")
        ),
        sa.CheckConstraint(
            "returned_at IS NULL OR returned_at >= left_at",
            name=op.f("ck_outings_returned_after_leaving"),
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["users.id"],
            name=op.f("fk_outings_student_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outings")),
    )
    op.create_index("ix_outings_student_left", "outings", ["student_id", "left_at"], unique=False)
    op.create_index(
        "uq_outings_one_open_per_student",
        "outings",
        ["student_id"],
        unique=True,
        postgresql_where=sa.text("returned_at IS NULL"),
    )
    # ### end Alembic commands ###
    # Every table denies Supabase's Data API (see 0002).
    op.execute("ALTER TABLE outings ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_outings_one_open_per_student",
        table_name="outings",
        postgresql_where=sa.text("returned_at IS NULL"),
    )
    op.drop_index("ix_outings_student_left", table_name="outings")
    op.drop_table("outings")
    # ### end Alembic commands ###
